parameter ALU_PASS      = 5'h00;
parameter ALU_ADD       = 5'h01;
parameter ALU_SUB       = 5'h02;
parameter ALU_MUL       = 5'h03;
parameter ALU_DIV       = 5'h04;
parameter ALU_NEG       = 5'h05;
parameter ALU_NOT       = 5'h06;
parameter ALU_AND       = 5'h08;
parameter ALU_OR        = 5'h09;
parameter ALU_XOR       = 5'h0A;
parameter ALU_SHL       = 5'h0B;
parameter ALU_SHR       = 5'h0C;
parameter ALU_LEN       = 5'h0D;
parameter ALU_TEST      = 5'h0E;
parameter ALU_CMP_EQ    = 5'h0F;
parameter ALU_CMP_LT    = 5'h10;
parameter ALU_CMP_LE    = 5'h11;
parameter ALU_CMP_GT    = 5'h12;
parameter ALU_CMP_GE    = 5'h13;
parameter ALU_FORLOOP   = 5'h14;
parameter ALU_CONCAT    = 5'h15;
parameter ALU_MOD       = 5'h16;
parameter ALU_POW       = 5'h17;
parameter ALU_IDIV      = 5'h18;
parameter ALU_LOADNIL   = 5'h19;
parameter ALU_LOADFALSE = 5'h1A;
parameter ALU_LOADTRUE  = 5'h1B;

parameter ALUOPTYPE_NORMAL  = 2'b00;
parameter ALUOPTYPE_BINARY = 2'b01;
parameter ALUOPTYPE_LOGIC  = 2'b10;

parameter DEST_NONE          = 4'b0000;
parameter DEST_REG_A         = 4'b0001;
parameter DEST_UPVALUE_B     = 4'b0010;
parameter DEST_TEMPTABLE     = 4'b0011;
parameter DEST_TEMP_K_B      = 4'b0100; // temp table[K[B]] (for Upvalue[A][K[B]])
parameter DEST_TEMP_REG_B    = 4'b0101; // temp table[R[B]] (for R[A][R[B]])
parameter DEST_REG_A_PLUS_1  = 4'b0110; // R[A+1]
parameter DEST_REG_A_UNTIL_B = 4'b0111; // R[A], R[A+1], ... R[A+B]
parameter DEST_REG_A_CALL    = 4'b1000; // R[A], ... , R[A+C-2]
parameter DEST_TEMP_B        = 4'b1001; // B
parameter DEST_PC            = 4'b1111;

parameter SOURCE_ZERO       = 5'b00000;
parameter SOURCE_REG_A      = 5'b00001;
parameter SOURCE_REG_B      = 5'b00010;
parameter SOURCE_REG_C      = 5'b00011;
parameter SOURCE_K_B        = 5'b00100; // K[Bx]
parameter SOURCE_K_EXTRA    = 5'b00101; // K[EXTRAARG.Ax]
parameter SOURCE_K_C        = 5'b00110; // K[C]
parameter SOURCE_SC         = 5'b00111; // sC
parameter SOURCE_FC         = 5'b01000; // (number)sC
parameter SOURCE_SAX        = 5'b01001; // sAx
parameter SOURCE_UPVALUE_A  = 5'b01010; // Upvalue[A]
parameter SOURCE_UPVALUE_B  = 5'b01011; // Upvalue[B]
parameter SOURCE_TEMPTABLE  = 5'b01100; // temp table
parameter SOURCE_TEMP_B     = 5'b01101; // temp table[B] (for R[A][B])
parameter SOURCE_TEMP_K_C   = 5'b01110; // temp table[K[C]] (for Upvalue[B][K[C]])
parameter SOURCE_TEMP_REG_C = 5'b01111; // temp table[R[C]] (for R[B][R[C]])
parameter SOURCE_REGK_C     = 5'b10000; // RK[C] - register or constant C
parameter SOURCE_NEWTABLE   = 5'b10001; // {}
parameter SOURCE_TEMP_REGK_C = 5'b10010; // temp table[R[C] or K[C]] (for OP_SELF R[B][RK[C]])
parameter SOURCE_TEMP_C     = 5'b10011; // temp table[C] (for OP_SELF R[B][RK[C]])
parameter SOURCE_PC         = 5'b11111;