`define OP_MOVE       7'h00 
`define OP_LOADI      7'h01 
`define OP_LOADF      7'h02 
`define OP_LOADK      7'h03 
`define OP_LOADKX     7'h04 
`define OP_LOADFALSE  7'h05 
`define OP_LFALSESKIP 7'h06 
`define OP_LOADTRUE   7'h07 
`define OP_LOADNIL    7'h08 
`define OP_GETUPVAL   7'h09 
`define OP_SETUPVAL   7'h0A 
`define OP_GETTABUP   7'h0B 
`define OP_GETTABLE   7'h0C 
`define OP_GETI       7'h0D 
`define OP_GETFIELD   7'h0E 
`define OP_SETTABUP   7'h0F 
`define OP_SETTABLE   7'h10 
`define OP_SETI       7'h11 
`define OP_SETFIELD   7'h12 
`define OP_NEWTABLE   7'h13 
`define OP_SELF       7'h14 
`define OP_ADDI       7'h15 
`define OP_ADDK       7'h16 
`define OP_SUBK       7'h17 
`define OP_MULK       7'h18 
`define OP_MODK       7'h19 
`define OP_POWK       7'h1A 
`define OP_DIVK       7'h1B 
`define OP_IDIVK      7'h1C 
`define OP_BANDK      7'h1D 
`define OP_BORK       7'h1E 
`define OP_BXORK      7'h1F 
`define OP_SHRI       7'h20 
`define OP_SHLI       7'h21 
`define OP_ADD        7'h22 
`define OP_SUB        7'h23 
`define OP_MUL        7'h24 
`define OP_MOD        7'h25 
`define OP_POW        7'h26 
`define OP_DIV        7'h27 
`define OP_IDIV       7'h28 
`define OP_BAND       7'h29 
`define OP_BOR        7'h2A 
`define OP_BXOR       7'h2B 
`define OP_SHL        7'h2C 
`define OP_SHR        7'h2D 
`define OP_MMBIN      7'h2E 
`define OP_MMBINI     7'h2F 
`define OP_MMBINK     7'h30 
`define OP_UNM        7'h31 
`define OP_BNOT       7'h32 
`define OP_NOT        7'h33 
`define OP_LEN        7'h34 
`define OP_CONCAT     7'h35 
`define OP_CLOSE      7'h36 
`define OP_TBC        7'h37 
`define OP_JMP        7'h38 
`define OP_EQ         7'h39 
`define OP_LT         7'h3A 
`define OP_LE         7'h3B 
`define OP_EQK        7'h3C 
`define OP_EQI        7'h3D 
`define OP_LTI        7'h3E 
`define OP_LEI        7'h3F 
`define OP_GTI        7'h40 
`define OP_GEI        7'h41 
`define OP_TEST       7'h42 
`define OP_TESTSET    7'h43 
`define OP_CALL       7'h44 
`define OP_TAILCALL   7'h45 
`define OP_RETURN     7'h46 
`define OP_RETURN0    7'h47 
`define OP_RETURN1    7'h48 
`define OP_FORLOOP    7'h49 
`define OP_FORPREP    7'h4A 
`define OP_TFORPREP   7'h4B 
`define OP_TFORCALL   7'h4C 
`define OP_TFORLOOP   7'h4D 
`define OP_SETLIST    7'h4E 
`define OP_CLOSURE    7'h4F 
`define OP_VARARG     7'h50 
`define OP_VARARGPREP 7'h51 
`define OP_EXTRAARG   7'h52 
